### ISSUE TITLE
Files upload not working

### ISSUE THREAD

**Issue by cclecle** [proxmoxer/proxmoxer#116] opened 2022-10-31 00:23 UTC
Not sure since when but I can not get files uploading to work using proxmoxer.

See my thread on proxmox forum:
[Proxmox Forum](https://forum.proxmox.com/threads/storage-rest-api-error-no-space-left-on-device.117296/)

Copy of the thread:

Hi,

Using proxmoxer I am trying to upload lxc template to my hypervisor.
It used to work just fine but since a few weeks (or month) it fails.

On proxmoxer side it say:
Remote end closed connection without response

Then I checked on hypervisor side:
In /var/log/syslog :
Oct 30 22:01:55 hypervisor pveproxy[2126784]: problem with client ::ffff:XXX.XXX.XXX.XXX; No space left on device
In /var/log/pveproxy/ :
::ffff:XXX.XXX.XXX.XXX- dabfactory-bot@pam!XXXXXXXXXXXX[30/10/2022:22:04:34 +0100] "POST /api2/json/nodes/hypervisor/storage/WORK/upload HTTP/1.1" 500 -

There is plenty of space:
Sys. de fichiers Taille Utilisé Dispo Uti% Monté sur
udev 16G 0 16G 0% /dev
tmpfs 3,2G 13M 3,2G 1% /run
/dev/mapper/pve-root 28G 13G 14G 50% /
tmpfs 16G 49M 16G 1% /dev/shm
tmpfs 5,0M 4,0K 5,0M 1% /run/lock
/dev/mapper/pve-data 65G 17G 49G 26% /var/lib/vz
/dev/sdc1 4,6T 4,2T 374G 92% /mnt/BRICK2
/dev/sdb1 4,6T 4,3T 345G 93% /mnt/BRICK1
/dev/fuse 128M 24K 128M 1% /etc/pve
tmpfs 3,2G 32K 3,2G 1% /run/user/0
localhost:TMP_FAST 100G 0 100G 0% /media/TMP_FAST
localhost:ARRAY 11T 11T 752G 94% /media/ARRAY
localhost:WORK 3,7T 3,4T 252G 94% /media/WORK

What I have try:
* Differents users: root@pam, or an authentification token, does not change anything.
* Tried with 2 differents storages, also not change anything
* Restarting the Node, also not change anything
* Other command like Str.status.get() work fine, for instance:
{'shared': 0, 'total': 3998318010368, 'active': 1, 'type': 'dir', 'content': 'vztmpl,rootdir', 'used': 3727743836160, 'enabled': 1, 'avail': 270574174208}
* It is working well using the proxmox WebGUI...

Other info:
proxmox VE version: 7.2-11
proxmoxer version: 1.3.1

EDIT 1:
test using pveproxy start --debug=1 :
worker[2323338]: PVE::APIServer::AnyEvent +1714: (eval): ACCEPT FH10 CONN0
worker[2323338]: PVE::APIServer::AnyEvent +1325: (eval): start upload /api2/json/nodes/hypervisor/storage/local/upload multipart/form-data e4e26ace364a4f9488cf9a9f06dbc860
worker[2323338]: PVE::APIServer::AnyEvent +1764: client_do_disconnect: close connection AnyEvent::Handle=HASH(0x559afd76bfd8)
worker[2323338]: PVE::APIServer::AnyEvent +1764: client_do_disconnect: CLOSE FH10 CONN0

Compared to through webGUI:
(...)
worker[2326306]: PVE::APIServer::AnyEvent +1325: (eval): start upload /api2/json/nodes/hypervisor/storage/local/upload multipart/form-data ---------------------------221127871937183401032155461004
(...)

EDIT2:
Seems to work using low-level API (requests + requests_toolbelt)....
So not a Proxmox issue, will make a ticket on proxmoxer-side.. !

Working sample:

```
import requests
from requests_toolbelt.multipart.encoder import MultipartEncoder

SERV_ADDR="https://XXX.XXX.XXX.XXX:8006"
NODE_NAME="XXXX"
STORAGE_NAME="XXXX"
FILENAME="XXXX"
FILEPATH=FILENAME #if same dir as script


mp_encoder = MultipartEncoder(
    fields={
        'filename'    : (FILENAME, open(FILEPATH, 'rb'), 'text/plain'),
    }
)

data = {
        'username'  : "root@pam",
        'password'  : "XXXXXXXXXXXX",
}

res = requests.post(    SERV_ADDR + '/api2/json/access/ticket',
                data = data,
                verify  =False)
ticket = res.json()["data"]["ticket"]
print(ticket)
CSRFPreventionToken = res.json()["data"]["CSRFPreventionToken"]
print(CSRFPreventionToken)

headers={
        'CSRFPreventionToken' : CSRFPreventionToken,
        'Content-Type': mp_encoder.content_type
 }
 
cookies={
    'PVEAuthCookie':ticket
    }

res = requests.post(    SERV_ADDR + '/api2/json/nodes/'+NODE_NAME+'/storage/'+STORAGE_NAME+'/upload',
                headers = headers,
                cookies = cookies,
                data    = mp_encoder,
                verify  =False)
print(res.json())

```

**Comment by jhollowe** [comment] 2022-10-31 20:52
What version of PVE, python, and proxmoxer are you using? What file are you trying to upload?

**Comment by cclecle** [comment] 2022-10-31 22:16
PVE 7.2-11
Python 3.9.2 (Linux) + Python 3.9.5 (windows)
Proxmoxer 1.3.1

Trying to upload a .tar.gz lxc appliance template

Was able to fix it modifying proxmoxer:
https://github.com/cclecle/proxmoxer/commit/07924b7edf2b9089d4485647c146f53bc081c479

Would not lie, I found this fix by comparing with working solution, not sure why 'text/plain' content type is needed now (and was not). But it is doing the trick !

**Comment by jhollowe** [comment] 2022-11-01 16:00
What is the python code you are running when it fails. It does seem strange that the type needs to be "text/plain"

**Comment by cclecle** [comment] 2022-11-11 20:33
Sorry for delay.
I already sent you template but I reworked it, just change values according your need.
Reproduce defect in both plain-auth and api token.
This script tested only on windows, but should also work on Linux..

`import requests
import os
from requests_toolbelt.multipart.encoder import MultipartEncoder
from pprint import pprint

###############
## CONFIG
SERV_ADDR="https://XX.XX.XX.XX:8006"
FILEPATH='\\'
FILENAME="XXXXXXXXX.tar.gz"
STORAGENAME="XXXXX"
UseAPIToken=True
PLAINAUTH_USERNAME="root@pam"
PLAINAUTH_PASSWORD="XXXXXXX"
APITOKEN_STRING="PVEAPIToken=XXXXXX@pam!XXXXXXXXXXX=XXXXXXXX"
Defect=False  # <<==== Here !




###############
## JOB
FILEFULLPATH=os.path.join(FILEPATH,FILENAME)
mp_encoder=None
if Defect:
    mp_encoder = MultipartEncoder(
        fields={
            'content' : "vztmpl",
            'filename'    : (FILENAME, open(FILEFULLPATH, 'rb')),
        }
    )
else:
    mp_encoder = MultipartEncoder(
        fields={
            'content' : "vztmpl",
            'filename'    : (FILENAME, open(FILEFULLPATH, 'rb'), 'text/plain'),
        }
    )

headers={}
headers['Content-Type'] = mp_encoder.content_type
cookies={}

if not UseAPIToken:
    data = {
            'username'  : PLAINAUTH_USERNAME, 
            'password'  : PLAINAUTH_PASSWORD,
    }

    res = requests.post(    SERV_ADDR + '/api2/json/access/ticket',
                    data = data,
                    verify  =False)
    print(res.json())
    ticket = res.json()["data"]["ticket"]
    print(ticket)
    CSRFPreventionToken = res.json()["data"]["CSRFPreventionToken"]
    print(CSRFPreventionToken)

    headers['CSRFPreventionToken'] = CSRFPreventionToken
    cookies['PVEAuthCookie'] = ticket
else:
    headers['Authorization '] = APITOKEN_STRING
    
    
pprint("===START===")
for var in [    mp_encoder,
                headers,
                cookies,]:
    try:
        pprint(json.dumps(var))
    except:
        pprint(var)
        
                
res = requests.post(    SERV_ADDR + '/api2/json/nodes/hypervisor/storage/'+STORAGENAME+'/upload',
                headers = headers,
                cookies = cookies,
                data    = mp_encoder,
                verify  =False)
print(res.json())
`

**Comment by jhollowe** [comment] 2022-11-11 21:15
is `self.node` an instance of `self.proxmox.nodes("your_node_name")`?

I'll try to reproduce the issue using your promoxer example code

**Comment by cclecle** [comment] 2022-11-11 22:11
> 

Yes excatly, it is !

**Comment by jhollowe** [comment] 2022-11-12 15:29
What version of proxmoxer was this working for you previously?

**Comment by cclecle** [comment] 2022-11-12 17:21
Unfortunatly I can not remember ... Not even sur it is a proxmoxer update or a dependency or a proxmox :-/
`self.CfgMng.template_storage` is just a string containing storage name.

**Comment by jhollowe** [comment] 2022-11-12 18:03
Hrm, I reproduced with the same proxmoxer (1.3.1) and python (3.7.13) against `7.2-7` (`d0dd0e85`) and `7.2-11` (`b76d3178`) using the [alpine 3.16]( http://download.proxmox.com/images/system/alpine-3.16-default_20220622_amd64.tar.xz) template. 

The issue is only present on my `7.2-11` node. If you are able, please try on a previous version of PVE. Also if you are able, try using one of the ssh backends to try the upload.

I'm going to keep looking at this and try to figure if we can make a change to proxmoxer to support `7.2-11` or if this is a PVE bug that should be fixed on the Proxmox side of things.

**Comment by jhollowe** [comment] 2022-11-12 20:24
I've done a packet capture against 7.1-7 (the latest ISO I had on hand) and 7.2-11 (same PVE node updated to latest). From what I can tell there is nothing wrong on the client side (the upload is the exact same request with different auth and multipart boundary). The request goes through fine and then hits the `client_do_disconnect: close connection AnyEvent::Handle` in the pveproxy which then sends an RST to the client.

It looks like this is an issue with PVE, so I'm going to label it as such but leave this issue open until it gets resolved.

[captures.zip](https://github.com/proxmoxer/proxmoxer/files/9995836/captures.zip)

**Comment by cclecle** [comment] 2022-11-12 22:29
I do not have proxmox test environnent sorry :(.
For the moment I can live with my patched version...

I made a quick check on proxmox web UI, the encoding it also set !

See:
![image](https://user-images.githubusercontent.com/15073640/201496980-5da672df-28bf-41cc-b118-b3840bf6aa05.png)

Value is not the same but there is one... !

Maybe we can just consider this is the way to go ?
And fix my patch to use application/x-gzip like PVE UI is doing... ?

**Comment by jhollowe** [comment] 2022-11-13 23:51
It looks like a [pve-http-server commit from May](https://git.proxmox.com/?p=pve-http-server.git;a=commitdiff;h=0fbcbc26289944bb28ae4bf488f352be251d8948;ds=sidebyside) (inadvertently?) requires a Content-Type for the file's multipart part but it never uses the value.

I've raised bug [4344](https://bugzilla.proxmox.com/show_bug.cgi?id=4344) to remove this requirement and have submitted a fix to the mailing list.

**Comment by cclecle** [comment] 2022-11-15 11:14
Right, but if you look the full issue:
- previous version of PVE dont care about content-type
- the GUI is using content-type
- if they 'fix' ( more a revert than a fix cause its not 'broken'), proxmoxer will work with new versions but not with olds

On the other hand, adding content-type to proxmoxer will solve the current issue and will not cause problem with older proxmox...
So for users I guess a proxmoxer-side fix would be prefered, even if I agree with the fact that the initial break comes from proxmox side..

**Comment by jhollowe** [comment] 2022-11-22 02:20
Since PVE has regular updates and there is not a big reason to not update to the point releases, I'm hesitant to make a proxmoxer code change to add extra stuff which just increases the likelihood of breakage in the future. The error was only in a few point (or dash?) releases and so I don't see a reason to add a change to proxmoxer which is only relevant for a few versions which will be upgraded from in a few weeks/months.

**Closed** 2022-11-22 02:33 UTC
Labels: type:bug :lady_beetle:, backend:https, status:proxmox-issue

**Comment by cclecle** [comment] 2022-11-22 19:44
Checked RFC: [RFC 2388 ](https://www.ietf.org/rfc/rfc2388.txt)
=>§3 says: _As with all multipart MIME types, each part has an **optional** "Content-Type", which defaults to text/plain_
So you are right, it is a regression as the standard do not state requirement for this field..
